### ISSUE TITLE
This is sweet! Now direct BIG-REQUESTS?

### ISSUE THREAD

**Issue by etale-cohomology** [abainbridge/x11_socket#1]
Man this is awesome.

BTW my main reason for trying to do this was to send raw `PUT_IMAGE` requests. However, there's a `16-bit` limit (or something) on the image buffer size (or something), so if you want to send a full `1920x1080` image, you have 2 options:

0) split your image into small tiles and send several `PUT_IMAGE` requests
1) use the `BIG-REQUESTS` **extension** and send the full `1920x1080` image at once

I never figured out how to use `BIG-REQUESTS` this way, though.

Let me know if you do!

 (btw credit for the code should go to the guy I learned to do this from, but I still can't find that stupid website!)

**Comment by abainbridge** [comment]
I couldn't get PutImage to work with BIG-REQUESTS either. The protocol spec says that big-requests implementations only need to support it on certain requests and PutImage isn't one of them. See Chapter 5 in https://www.x.org/releases/X11R7.7/doc/bigreqsproto/bigreq.html

Requests like PolyLine aren't possible to break into smaller requests without damaging the resulting image. That is the main thing they wanted to fix with big-requests, so I guess they didn't care about PutImage, in the Linux X11 implementation

I've put my code that splits PutImage requests into chunks over here. It has to handle the case where the X server refuses to accept more data on the socket by retrying: https://github.com/abainbridge/deadfrog-lib/blob/master/src/df_window_x11.cpp

The really correct way to send bitmaps to the X server is the Present extension: https://cgit.freedesktop.org/xorg/proto/presentproto/tree/presentproto.txt

**Comment by abainbridge** [comment]
I've since learned the the Present extension isn't very helpful either and should use the MIT-SHM extension. See https://lists.x.org/archives/xorg/2021-August/060766.html.
