### ISSUE TITLE
Problems with an implementation in c++

### ISSUE THREAD

**Issue by robscardi** [abainbridge/x11_socket#2]
Greetings. I wanted to contact you privately but I couldn't find a way, and I'm sorry if this isn't the place for such questions. For some time I tried to create my own implementation in C++ for a direct connection to the Xserver, but I'm new to socket programming and I couldn't figure out what's going wrong with my code, considered that is pratically identical to yours just incapsulated in object and stuff(I tried to use asiolib and more "C++-esque" way to do the thing, but even then i couldn't make it work). I tried to debug with socat, the problem is that the server doesn't respond to my signals, initial connection data in particularly. I verified that what my program sends to the socket is the same that your does. What I have now it's a very basic thing with just a class. Is it ok to ask for help here? Can I link the repository?

**Comment by abainbridge** [comment]
I think you've got the wrong length in your connection request. You say:
 init_data.auth_proto_data_len = 20;
Try changing the value to 16.

If you're still stuck, you can get me on andy at deadfrog co uk.

**Comment by robscardi** [comment]
It really worked, thanks, I can't believe it was really just that. So, considering that this part of it's just your, would you like to be cited when and if this thing will become usable (I doubt it will but just in case)?

**Comment by abainbridge** [comment]
Hah, yeah, I've been blocked by similarly trivial errors many times myself. I just built your app and did "strace my_app", "strace your_app" and compared the results. I ignored all the stuff libc and libc++ do at startup and started reading when the socket was opened. I only had to read 10 lines to find the error. I don't feel like I need any credit!

**Comment by robscardi** [comment]
Thank you kindly
